package resources

type HttpResponseCODE struct {
	OK      int
	CREATED int

	UNAUTHORIZATION int

	VAULT_SERVER_ERROR int

	FAILED_CREATE_KEYID   int
	FAILED_CREATE_PRIVKEY int
	FAILED_STORE_PRIVKEY  int

	INVALID_PARAM_KEYID         int
	INVALID_PARAM_SERIALIZEDTXN int

	NON_EXIST_KEYID int

	FAILED_QUERY_PRIVKEY             int
	FAILED_HEX_TO_ECDSA              int
	FAILED_PARSE_TXN_EVM             int
	FAILED_SIGN_TXN_EVM              int
	FAILED_MARSHAL_BINARY_SIGNED_TXN int
}

var HCode HttpResponseCODE

func SetHCode() {

	HCode.OK = 200
	HCode.CREATED = 201

	HCode.UNAUTHORIZATION = 401

	HCode.VAULT_SERVER_ERROR = 408

	HCode.FAILED_CREATE_KEYID = 611
	HCode.FAILED_CREATE_PRIVKEY = 612
	HCode.FAILED_STORE_PRIVKEY = 613

	HCode.FAILED_QUERY_PRIVKEY = 621
	HCode.FAILED_HEX_TO_ECDSA = 622
	HCode.FAILED_PARSE_TXN_EVM = 623
	HCode.FAILED_SIGN_TXN_EVM = 624
	HCode.FAILED_MARSHAL_BINARY_SIGNED_TXN = 625

	HCode.INVALID_PARAM_KEYID = 701
	HCode.INVALID_PARAM_SERIALIZEDTXN = 702

	HCode.NON_EXIST_KEYID = 703

}

// parameter 정합성 검증 [keyID, serializedTxn]
// https 인증 적용
// logging 적용
